Add Text change listener and alert dialog
AM-Kitty/iAnime pull request #1
Opened 2023-03-15 23:59 UTC by AM-Kitty

## Work Description

- Add Text change listener
- Add exit before dialog
- Add navigate back customized behavior

2023-03-16 00:08 UTC, Tony-Feng requested changes

2023-03-16 00:08 UTC, Tony-Feng commented on app/src/main/res/values-zh/strings.xml
> +    <string name="exit_dialog_message">确认直接退出吗?</string>
In order to be consistent, change the question mark to `？` instead of `?`, which should be `确认直接退出吗？`

2023-03-16 00:08 UTC, Tony-Feng commented on app/src/main/java/com/project/ianime/screen/ManageAnimeFragment.kt
> +            true
Does this line only have `true`?

2023-03-16 01:19 UTC, AM-Kitty commented on app/src/main/java/com/project/ianime/screen/ManageAnimeFragment.kt
> +            true
yes, it needs to return a Boolean value

2023-03-29 17:37 UTC, Tony-Feng approved these changes
LGTM!

2023-03-29 19:34 UTC, merged