Add anime detail page UI
AM-Kitty/iAnime pull request #4
Opened 2023-08-26 18:36 UTC by AM-Kitty

## Work Summary
- Add anime detail screen
- Add get single anime by id method in viewmodel
- Add Picasso image handling
- Add mappings between api model and data model

2023-08-27 19:15 UTC, Tony-Feng requested changes

2023-08-27 19:15 UTC, Tony-Feng commented on app/src/main/java/com/project/ianime/utils/image/ImageUtils.kt
> +        return Base64.encodeToString(bytes, Base64.DEFAULT)
this func is not in use?

2023-08-27 19:15 UTC, Tony-Feng commented on app/src/main/java/com/project/ianime/utils/image/ImageUtils.kt
> +                                Log.i("Picasso", "Could not fetch image")
can add img url in log

2023-08-27 19:15 UTC, Tony-Feng commented on app/src/main/res/values-zh/strings.xml
> +    <string name="empty_description_message">我们需要迷迷提供更多关于这个动漫的信息。。。</string>
`迷迷`?

2023-08-27 19:15 UTC, Tony-Feng commented on app/src/main/res/values/strings.xml
> +    <string name="empty_description_message">We need you input some more information for this anime …</string>
remove space and replace to `.`: `We need you to provide more information about this anime...`

2023-08-27 19:16 UTC, Tony-Feng commented
actually no need to squash commits, since it doesn't have limit on that

2023-08-27 19:39 UTC, AM-Kitty commented on app/src/main/java/com/project/ianime/utils/image/ImageUtils.kt
> +        return Base64.encodeToString(bytes, Base64.DEFAULT)
leave it as backup

2023-08-27 20:09 UTC, Tony-Feng commented on app/src/main/res/values/strings.xml
> +    <string name="empty_description_message" tools:ignore="TypographyEllipsis">We need you input some more information for this anime...</string>
you can directly use this: `We need you to provide more information about this anime...`

2023-08-28 02:52 UTC, Tony-Feng approved these changes
LGTM!

2023-08-28 02:52 UTC, merged